import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React from 'react';
import CoinFlip from '../components/CoinFlip';
import ContractInfos from '../components/ContractInfos';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coin Flip App - ETH + Chainlink</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="public/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <h1 className={styles.title}>Coin Flip App</h1>
        <CoinFlip />
        <ContractInfos />
      </main>

      <footer className={styles.footer}>
        <a href="#" rel="noopener noreferrer" target="_blank">
          Coin Flip dApp built by D.Gadiou & A.GomezDelToro
        </a>
      </footer>
    </div>
  );
};

export default Home;
